api_host: http://google.com/?q=desarrollandoamericalatina
twitter:
  consumer_key       : '#############'
  consumer_secret    : '##################################################'
  oauth_token        : '############=#####################################'
  oauth_token_secret : 'eU2yA80Sx28ETisrsYwxmw2PQoQUxTufyPBaKRk'
  hashtags           : [ '#ombuduy', '#OMBUDUY', '#OmbudUy', '#OmbudUY', '#ombudUY', '#ombudUy' ]
